<x-layouts.app title="New exchange">
    <div class="mb-7"><a href="{{ route('exchanges.index') }}" class="text-sm underline">Exchanges</a><h1 class="mt-2 text-3xl font-bold">New exchange</h1><p class="mt-3 text-sm text-text-secondary">Exchange for another size, colour or product within three days (72 hours) of purchase.</p></div>
    <form method="GET" class="mb-6 flex flex-wrap items-end gap-4"><x-input name="sale_number" label="Original sale number" :value="$sale?->sale_number ?? request('sale_number')" required maxlength="100" /><x-button type="submit" variant="secondary">Find sale</x-button></form>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    @if($sale)<form method="POST" action="{{ route('exchanges.store') }}" x-data="saleForm({id:'',label:''}, @js($lines), @js(route('exchanges.lookup')), true)" class="space-y-6">@csrf<input type="hidden" name="sale_id" value="{{ $sale->id }}"><input type="hidden" name="request_key" value="{{ $requestKey }}">
    <x-card title="Items being returned"><p class="mb-5 text-sm">Complete by {{ $deadline->format('d M Y H:i:s T') }}. Leave quantity at 0 for items not being exchanged.</p><div class="space-y-4">@foreach($sale->items as $index => $item)<fieldset class="rounded-lg border border-border p-4"><legend class="max-w-full break-words px-2 text-sm font-semibold">{{ $item->variant->sku }} · {{ $item->variant->product->name }}</legend><input type="hidden" name="returned_items[{{ $index }}][sale_item_id]" value="{{ $item->id }}"><p class="mb-4 text-sm">Remaining: {{ $remaining[$item->id] }} · Original discounted line total: TZS {{ $item->line_total }}</p><div class="grid gap-4 sm:grid-cols-2"><x-input :name="'returned_items['.$index.'][quantity]'" :id="'returned-quantity-'.$index" label="Return quantity" type="number" min="0" :max="$remaining[$item->id]" :value="old('returned_items.'.$index.'.quantity', 0)" required /><x-select :name="'returned_items['.$index.'][condition]'" :id="'returned-condition-'.$index" label="Condition" required>@foreach(\App\Services\ReturnService::CONDITIONS as $condition)<option value="{{ $condition }}" @selected(old('returned_items.'.$index.'.condition') === $condition)>{{ $condition }}</option>@endforeach</x-select></div></fieldset>@endforeach</div></x-card>
    <x-card title="Choose replacements"><label for="product-search" class="mb-2 block text-sm font-medium">Product name or SKU</label><div class="flex gap-3"><input id="product-search" x-model="query" @keydown.enter.prevent="search('variant')" class="min-w-0 flex-1 rounded-lg border border-border px-3 py-2" maxlength="191"><x-button type="button" variant="secondary" @click="search('variant')">Search products</x-button></div><p role="status" class="mt-3 text-sm" x-text="error"></p><div class="my-4 grid gap-3 sm:grid-cols-2"><template x-for="result in results" :key="result.id"><button type="button" @click="add(result)" class="rounded-lg border border-border p-4 text-left text-sm hover:bg-selected"><span class="block break-words font-semibold" x-text="result.label"></span><span class="mt-2 block" x-text="'TZS ' + result.unit_price + ' · Available: ' + result.available"></span></button></template></div>
    <div class="space-y-4"><template x-for="(line, index) in lines" :key="line.product_variant_id"><fieldset class="rounded-lg border border-border p-4"><legend class="max-w-full break-words px-2 text-sm font-semibold" x-text="line.label"></legend><input type="hidden" :name="`replacement_items[${index}][product_variant_id]`" :value="line.product_variant_id"><p class="mb-3 text-sm" x-text="'Catalogue price: TZS ' + line.unit_price"></p><label :for="'replacement-quantity-' + index" class="mb-2 block text-sm">Replacement quantity</label><input :id="'replacement-quantity-' + index" :name="`replacement_items[${index}][quantity]`" x-model="line.quantity" required type="number" min="1" class="w-full rounded-lg border border-border px-3 py-2"><button type="button" @click="lines.splice(index, 1)" class="mt-3 min-h-11 text-sm underline">Remove replacement</button></fieldset></template></div></x-card>
    <x-input name="reason" label="Exchange reason" :value="old('reason')" required maxlength="255" /><x-input name="notes" label="Notes (optional)" :value="old('notes')" maxlength="5000" /><x-button type="submit" x-bind:disabled="!lines.length">Save and review exchange</x-button><p class="text-sm text-text-secondary">The server calculates final values. Saving does not reserve or move stock.</p></form>@endif
</x-layouts.app>
