<x-layouts.app :title="$exchange->exchange_number">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('exchanges.index') }}" class="text-sm underline">Exchanges</a><h1 class="mt-2 text-3xl font-bold">{{ $exchange->exchange_number }}</h1></div><span class="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold">{{ $exchange->status->value }}</span></div>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <x-card title="Exchange review"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt>Original sale</dt><dd>{{ $exchange->sale->sale_number }}</dd></div><div><dt>Deadline</dt><dd>{{ $deadline?->format('d M Y H:i:s T') }}</dd></div><div><dt>Returned value</dt><dd class="text-lg font-semibold">@money($exchange->total_return_value)</dd></div><div><dt>Replacement value</dt><dd class="text-lg font-semibold">@money($exchange->total_replacement_value)</dd></div><div><dt>Customer pays</dt><dd class="text-lg font-semibold">@money($exchange->amount_due)</dd></div><div><dt>Refund due</dt><dd class="text-lg font-semibold">@money($exchange->refund_due)</dd></div></dl><p class="mt-5 break-words text-sm">{{ $exchange->reason }}</p><p class="mt-3 break-words text-sm">{{ $exchange->notes }}</p></x-card>
    @foreach(['RETURNED' => 'Returned items', 'REPLACEMENT' => 'Replacement items'] as $type => $heading)<div class="relative my-6 overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full min-w-[550px] text-left text-sm"><caption class="p-4 text-left font-semibold">{{ $heading }}</caption><thead><tr>@foreach(['Item', 'Quantity', 'Condition', 'Value (TZS)'] as $label)<th scope="col" class="p-4">{{ $label }}</th>@endforeach @can('products.view_cost')<th scope="col" class="p-4">Unit cost (TZS)</th>@endcan</tr></thead><tbody>@foreach($exchange->items->where('item_type', $type) as $item)<tr class="border-t border-border"><th scope="row" class="p-4 font-medium">{{ $item->variant->sku }}<span class="block">{{ $item->variant->product->name }}</span></th><td class="p-4">{{ $item->quantity }}</td><td class="p-4">{{ $item->condition ?? 'New replacement' }}</td><td class="p-4">{{ \App\Support\Money::format($item->line_total, false) }}</td>@can('products.view_cost')<td class="p-4">{{ $item->unit_cost !== null ? \App\Support\Money::format($item->unit_cost, false) : 'Captured on completion' }}</td>@endcan</tr>@endforeach</tbody></table></div>@endforeach
    @if($exchange->status === \App\Enums\ExchangeStatus::Pending)<div class="mb-6 flex flex-wrap gap-3" x-data>
    @if($deadline && now()->lte($deadline))
        @if($exchange->refund_due === '0.00' || (auth()->user()->role?->slug === 'administrator' && auth()->user()->hasPermission('refunds.approve') && auth()->user()->hasPermission('refunds.complete')))
        <x-button @click="$dispatch('open-modal', 'complete-exchange')">Complete exchange</x-button><x-modal name="complete-exchange" title="Confirm exchange and settlement"><form method="POST" action="{{ route('exchanges.complete', $exchange) }}" class="space-y-5">@csrf<p class="text-sm">Inspect the returned items and confirm replacement availability before settling. Only sellable returned items re-enter stock. Completion records all changes together.</p>
        @if($exchange->amount_due !== '0.00' || $exchange->refund_due !== '0.00')<p class="font-semibold">{{ $exchange->refund_due !== '0.00' ? 'Administrator refund approval: '.\App\Support\Money::format($exchange->refund_due) : 'Collect from customer: '.\App\Support\Money::format($exchange->amount_due) }}</p><x-select name="payment_method" label="Settlement method" required>@foreach(\App\Services\SaleService::PAYMENT_METHODS as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-select><x-input name="payment_reference" label="Payment reference (optional)" maxlength="191" /><label class="flex gap-3 text-sm"><input type="checkbox" name="settlement_confirmed" value="1" required>{{ $exchange->refund_due !== '0.00' ? 'I approve this refund and confirm the money was returned using the selected method.' : 'I confirm the additional payment was received using the selected method.' }}</label>@else<p class="text-sm">Same-value exchange. No additional payment or refund.</p>@endif
        <x-button type="submit">Confirm completion</x-button></form></x-modal>
        @else<p class="text-sm">An administrator must approve and complete this exchange because a refund is due.</p>@endif
    @else<p role="alert" class="text-sm text-danger">The three-day exchange window has expired.</p>@endif
    <x-button variant="secondary" @click="$dispatch('open-modal', 'cancel-exchange')">Cancel exchange</x-button><x-modal name="cancel-exchange" title="Cancel pending exchange"><form method="POST" action="{{ route('exchanges.cancel', $exchange) }}" class="space-y-5">@csrf<x-input name="reason" label="Cancellation reason" required maxlength="255" /><x-button type="submit" variant="danger">Confirm cancellation</x-button></form></x-modal></div>@endif
    <x-card title="History"><p class="text-sm">Created: {{ $exchange->created_at->format('d M Y H:i:s') }}</p>@if($exchange->processed_at)<p class="mt-3 text-sm">Completed: {{ $exchange->processed_at->format('d M Y H:i:s') }}</p>@endif @if($exchange->cancelled_at)<p class="mt-3 break-words text-sm">Cancelled: {{ $exchange->cancellation_reason }}</p>@endif @if($exchange->payment_method)<p class="mt-3 text-sm">Settlement: {{ \App\Services\SaleService::PAYMENT_METHODS[$exchange->payment_method] }} · {{ $exchange->payment_reference }}</p>@endif @if($exchange->refund)<p class="mt-3 text-sm">Refund: @can('refunds.create')<a class="underline" href="{{ route('refunds.show', $exchange->refund) }}">{{ $exchange->refund->refund_number }}</a>@else{{ $exchange->refund->refund_number }}@endcan</p>@endif</x-card>
</x-layouts.app>
