<x-layouts.app title="Audit logs">
    <h1 class="mb-3 text-3xl font-bold">Audit logs</h1><p class="mb-6 text-sm text-text-secondary">Read-only activity history. Dates use Africa/Dar_es_Salaam time.</p>
    <form method="GET" class="mb-6 grid gap-4 rounded-xl border border-border bg-surface p-5 sm:grid-cols-3">
        <x-select name="user_id" label="Staff member"><option value="">All staff</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user_id'] ?? '') == $user->id)>{{ $user->name }}</option>@endforeach</x-select>
        <x-select name="action" label="Action"><option value="">All actions</option>@foreach($actions as $action)<option @selected(($filters['action'] ?? '') === $action)>{{ $action }}</option>@endforeach</x-select>
        <x-select name="entity_type" label="Record type"><option value="">All types</option>@foreach($types as $type)<option @selected(($filters['entity_type'] ?? '') === $type)>{{ $type }}</option>@endforeach</x-select>
        <x-input name="entity_id" label="Record ID" type="number" min="1" :value="$filters['entity_id'] ?? ''" />
        <x-input name="date_from" label="From date" type="date" :value="$filters['date_from'] ?? ''" /><x-input name="date_to" label="To date" type="date" :value="$filters['date_to'] ?? ''" />
        <div class="flex items-center gap-4"><x-button type="submit">Filter</x-button><a href="{{ route('audit.index') }}" class="text-sm underline">Clear filters</a></div>
    </form>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><caption class="sr-only">Audit activity</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Date', 'Staff member', 'Action', 'Record'] as $label)<th scope="col" class="p-5">{{ $label }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@forelse($entries as $entry)<tr><th scope="row" class="p-5 font-medium"><a class="underline" href="{{ route('audit.show', $entry->id) }}">{{ $entry->created_at }}</a></th><td class="p-5">{{ $entry->actor_name ?? 'System / unavailable' }}</td><td class="p-5">{{ $entry->action }}</td><td class="p-5">{{ $entry->entity_type }} {{ $entry->entity_id === null ? '' : '#'.$entry->entity_id }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center">No matching audit records.</td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $entries->links() }}</div></div>
</x-layouts.app>