<x-layouts.app title="Purchase details">
    <a href="{{ route('purchases.index') }}" class="mb-5 inline-block text-sm underline">Back to purchases</a>
    <h1 class="text-3xl font-bold">{{ $purchase->status === \App\Enums\PurchaseStatus::Draft ? 'Review purchase draft' : 'Purchase details' }}</h1><p class="mb-7 mt-3 break-all text-sm text-text-secondary">{{ $purchase->purchase_number }}</p>
    @if(session('status'))<p role="status" class="mb-5 rounded-lg border border-success bg-surface p-4 text-sm">{{ session('status') }}</p>@endif
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger bg-surface p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <x-card class="mb-6"><dl class="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-3">
        <div><dt class="mb-2 text-text-secondary">Supplier</dt><dd class="break-words">{{ $purchase->supplier->name }}</dd></div><div><dt class="mb-2 text-text-secondary">Purchase date</dt><dd>{{ $purchase->purchase_date->format('d M Y') }}</dd></div><div><dt class="mb-2 text-text-secondary">Status</dt><dd><x-badge :tone="$purchase->status === \App\Enums\PurchaseStatus::Confirmed ? 'success' : 'info'">{{ $purchase->status->value }}</x-badge></dd></div>
        <div><dt class="mb-2 text-text-secondary">Supplier invoice</dt><dd class="break-words">{{ $purchase->supplier_invoice_number ?? 'Not provided' }}</dd></div><div><dt class="mb-2 text-text-secondary">Payment status (informational)</dt><dd>{{ str_replace('_', ' ', $purchase->payment_status) }}</dd></div><div><dt class="mb-2 text-text-secondary">Recorded by</dt><dd>{{ $purchase->creator->name }}</dd></div>
        @if($purchase->confirmed_at)<div><dt class="mb-2 text-text-secondary">Confirmed</dt><dd>{{ $purchase->confirmed_at->format('d M Y H:i') }} · {{ $purchase->confirmer->name }}</dd></div>@endif
    </dl>@if($purchase->notes)<p class="mt-5 whitespace-pre-line break-words text-sm">{{ $purchase->notes }}</p>@endif</x-card>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><caption class="sr-only">Purchase items and historical unit costs</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Product / SKU', 'Size / Colour', 'Quantity', 'Unit cost (TZS)', 'Line total (TZS)'] as $heading)<th scope="col" class="px-5 py-4 font-medium">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@foreach($purchase->items as $item)<tr><th scope="row" class="min-w-40 max-w-xs break-words px-5 py-4 font-medium">{{ $item->variant->product->name }}<span class="mt-1 block break-all text-xs text-text-secondary">{{ $item->variant->sku }}</span></th><td class="px-5 py-4">{{ $item->variant->size?->name ?? 'One size' }} / {{ $item->variant->colour?->name ?? 'No colour' }}</td><td class="px-5 py-4">{{ $item->quantity }}</td><td class="px-5 py-4">{{ \App\Support\Money::format($item->unit_cost, false) }}</td><td class="px-5 py-4">{{ \App\Support\Money::format($item->line_total, false) }}</td></tr>@endforeach</tbody></table></div><p class="border-t border-border p-5 text-right font-semibold">Total: @money($purchase->total_amount)</p></div>
    @if($purchase->status === \App\Enums\PurchaseStatus::Draft)
        <p class="my-6 text-sm text-text-secondary">Confirming receives every item into stock and updates average costs. Confirmed purchases cannot be edited or cancelled here.</p>
        <div class="flex flex-wrap items-center gap-4" x-data>
            <x-action-link :href="route('purchases.edit', $purchase)" :secondary="true">Edit draft</x-action-link>
            @can('inventory.adjust')<x-button type="button" @click="$dispatch('open-modal', 'confirm-purchase')">Confirm purchase</x-button>@endcan
            <x-button type="button" variant="secondary" @click="$dispatch('open-modal', 'cancel-purchase')">Cancel draft</x-button>
        </div>
        <x-modal name="confirm-purchase" title="Confirm purchase"><p class="mb-5 text-sm">Receive {{ $purchase->items->sum('quantity') }} units with a total cost of @money($purchase->total_amount)? This updates stock and average costs.</p><form method="POST" action="{{ route('purchases.confirm', $purchase) }}">@csrf<input type="hidden" name="revision" value="{{ $purchase->revision }}"><x-button type="submit">Confirm and receive stock</x-button></form></x-modal>
        <x-modal name="cancel-purchase" title="Cancel draft"><p class="mb-5 text-sm">Cancel this draft? It will remain in the purchase history and will not affect stock.</p><form method="POST" action="{{ route('purchases.cancel', $purchase) }}">@csrf<input type="hidden" name="revision" value="{{ $purchase->revision }}"><x-button type="submit" variant="secondary">Cancel this draft</x-button></form></x-modal>
    @endif
</x-layouts.app>
