<x-layouts.app title="Inventory movements">
    <a href="{{ route('inventory.index') }}" class="mb-5 inline-block text-sm underline">Back to inventory</a>
    <h1 class="text-3xl font-bold">Inventory movements</h1><p class="mb-7 mt-3 break-words text-sm text-text-secondary">{{ $variant->product->name }} · {{ $variant->sku }}</p>
    @if($variant->inventory)<x-card class="mb-6"><dl class="grid grid-cols-3 gap-4 text-sm">@foreach(['physical_quantity' => 'Physical', 'reserved_quantity' => 'Reserved', 'available_quantity' => 'Available'] as $field => $label)<div><dt class="text-text-secondary">{{ $label }}</dt><dd class="mt-2 text-xl font-bold">{{ $variant->inventory->$field }}</dd></div>@endforeach</dl></x-card>@endif
    <div class="overflow-hidden rounded-xl border border-border bg-surface">
        @if($movements->isEmpty())<p class="p-10 text-center text-sm text-text-secondary">No stock movements recorded for this variant.</p>
        @else<div class="relative overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><caption class="sr-only">Permanent stock movement ledger</caption><thead class="border-b border-border bg-background"><tr>@foreach(['When / Who', 'Movement', 'Physical change', 'Physical before → after', 'Reserved before → after', 'Reference / Reason'] as $heading)<th scope="col" class="px-5 py-4 font-medium">{{ $heading }}</th>@endforeach</tr></thead>
        <tbody class="divide-y divide-border">@foreach($movements as $movement)<tr><td class="whitespace-nowrap px-5 py-4">{{ $movement->created_at->format('d M Y H:i') }}<span class="mt-1 block text-xs text-text-secondary">{{ $movement->actor->name }}</span></td><td class="px-5 py-4">{{ str_replace('_', ' ', $movement->movement_type->value) }}</td><td class="px-5 py-4">{{ $movement->quantity_change > 0 ? '+' : '' }}{{ $movement->quantity_change }}</td><td class="px-5 py-4">{{ $movement->physical_quantity_before }} → {{ $movement->physical_quantity_after }}</td><td class="px-5 py-4">{{ $movement->reserved_quantity_before }} → {{ $movement->reserved_quantity_after }}</td><td class="min-w-40 max-w-xs break-words px-5 py-4">{{ $movement->reference_type }} #{{ $movement->reference_id }}@if($movement->reason)<p class="mt-1 text-xs">{{ $movement->reason }}</p>@endif @if($movement->notes)<p class="mt-1 text-xs text-text-secondary">{{ $movement->notes }}</p>@endif</td></tr>@endforeach</tbody></table></div><div class="border-t border-border p-5">{{ $movements->links() }}</div>@endif
    </div>
</x-layouts.app>
