<x-layouts.app title="New return">
    <div class="mb-7"><a href="{{ route('returns.index') }}" class="text-sm underline">Returns</a><h1 class="mt-2 text-3xl font-bold">New return</h1><p class="mt-3 text-sm text-text-secondary">Returns must be processed within 3 days (72 hours) of purchase. Use a receipt or the recorded sale as proof.</p></div>
    <form method="GET" class="mb-6 flex flex-wrap items-end gap-4"><x-input name="sale_number" label="Original sale number" :value="$sale?->sale_number ?? request('sale_number')" required maxlength="100" /><x-button type="submit" variant="secondary">Find sale</x-button></form>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    @if($sale)<form method="POST" action="{{ route('returns.store') }}" class="space-y-6">@csrf<input type="hidden" name="sale_id" value="{{ $sale->id }}"><input type="hidden" name="request_key" value="{{ $requestKey }}">
    <x-card :title="$sale->sale_number"><p class="mb-5 text-sm">Complete by {{ $deadline->format('d M Y H:i:s') }} ({{ config('app.timezone') }}). Enter 0 for items not being returned.</p><div class="space-y-4">@foreach($sale->items as $index => $item)<fieldset class="rounded-lg border border-border p-4"><legend class="max-w-full break-words px-2 text-sm font-semibold">{{ $item->variant->sku }} · {{ $item->variant->product->name }}</legend><input type="hidden" name="items[{{ $index }}][sale_item_id]" value="{{ $item->id }}"><p class="mb-4 text-sm">Sold: {{ $item->quantity }} · Remaining returnable: {{ $remaining[$item->id] }}</p><div class="grid gap-4 sm:grid-cols-2"><x-input :name="'items['.$index.'][quantity]'" :id="'quantity-'.$index" label="Return quantity" type="number" min="0" :max="$remaining[$item->id]" :value="old('items.'.$index.'.quantity', 0)" required /><x-select :name="'items['.$index.'][condition]'" :id="'condition-'.$index" label="Item condition" required>@foreach(\App\Services\ReturnService::CONDITIONS as $condition)<option value="{{ $condition }}" @selected(old('items.'.$index.'.condition') === $condition)>{{ $condition }}</option>@endforeach</x-select></div></fieldset>@endforeach</div></x-card>
    <x-card title="Reason and proof"><div class="grid gap-5 sm:grid-cols-2"><x-input name="reason" label="Return reason" :value="old('reason')" required maxlength="255" /><x-select name="proof_type" label="Proof available" required><option value="SALE_RECORD" @selected(old('proof_type') === 'SALE_RECORD')>Original sale in the system</option><option value="RECEIPT" @selected(old('proof_type') === 'RECEIPT')>Customer receipt</option></x-select><x-input name="proof_reference" label="Receipt reference (required if using receipt)" :value="old('proof_reference')" maxlength="191" /><x-input name="notes" label="Notes (optional)" :value="old('notes')" maxlength="5000" /></div></x-card>
    <x-button type="submit">Save for review</x-button><p class="text-sm text-text-secondary">Saving does not change stock or issue a refund.</p></form>@endif
</x-layouts.app>
