<x-layouts.app :title="$return->return_number">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('returns.index') }}" class="text-sm underline">Returns</a><h1 class="mt-2 text-3xl font-bold">{{ $return->return_number }}</h1></div><span class="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold">{{ $return->status->value }}</span></div>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <x-card title="Return details"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-text-secondary">Original sale</dt><dd class="mt-1">@can('sales.create')<a class="underline" href="{{ route('sales.show', $return->sale) }}">{{ $return->sale->sale_number }}</a>@else{{ $return->sale->sale_number }}@endcan</dd></div><div><dt class="text-text-secondary">Created by</dt><dd class="mt-1">{{ $return->processor->name }}</dd></div><div><dt class="text-text-secondary">Reason</dt><dd class="mt-1 break-words">{{ $return->reason }}</dd></div><div><dt class="text-text-secondary">Proof</dt><dd class="mt-1 break-words">{{ $return->proof_type === 'RECEIPT' ? 'Receipt' : 'Recorded sale' }} · {{ $return->proof_reference }}</dd></div><div><dt class="text-text-secondary">Return deadline</dt><dd class="mt-1">{{ $deadline?->format('d M Y H:i:s') }} ({{ config('app.timezone') }})</dd></div><div><dt class="text-text-secondary">Notes</dt><dd class="mt-1 break-words">{{ $return->notes ?? 'None' }}</dd></div></dl></x-card>
    <div class="relative my-6 overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full min-w-[550px] text-left text-sm"><caption class="sr-only">Returned merchandise</caption><thead><tr>@foreach(['Item', 'Quantity', 'Condition', 'Restored to stock'] as $label)<th scope="col" class="p-4">{{ $label }}</th>@endforeach</tr></thead><tbody>@foreach($return->items as $item)<tr class="border-t border-border"><th scope="row" class="p-4 font-medium">{{ $item->variant->sku }}<span class="block">{{ $item->variant->product->name }}</span></th><td class="p-4">{{ $item->quantity }}</td><td class="p-4">{{ $item->condition }}</td><td class="p-4">{{ $item->returned_to_stock ? 'Yes' : 'No' }}</td></tr>@endforeach</tbody></table></div>
    @can('products.view_cost')<p class="mb-5 text-sm">{{ $return->status === \App\Enums\ReturnStatus::Completed ? 'Historical COGS adjustment' : 'Proposed historical COGS adjustment' }}: TZS {{ $return->total_cost_adjustment }}</p>@endcan
    <p class="mb-6 text-sm text-text-secondary">Only sellable items are restored to stock on completion. This return does not issue a money refund.</p>
    <div class="mb-6 flex flex-wrap gap-3" x-data>
    @can('returns.approve')
        @if($eligible && $return->status === \App\Enums\ReturnStatus::Pending)<x-button @click="$dispatch('open-modal', 'approve-return')">Approve return</x-button><x-modal name="approve-return" title="Approve this return?"><p class="mb-5 text-sm">Confirm the original sale, proof, reason, quantities and item conditions shown above.</p><form method="POST" action="{{ route('returns.approve', $return) }}">@csrf<x-button type="submit">Confirm approval</x-button></form></x-modal>@endif
        @if($eligible && $return->status === \App\Enums\ReturnStatus::Approved)<x-button @click="$dispatch('open-modal', 'complete-return')">Complete return</x-button><x-modal name="complete-return" title="Process the returned items?"><p class="mb-5 text-sm">Confirm that these items have been received and inspected. Sellable quantities will be restored to stock once.</p><form method="POST" action="{{ route('returns.complete', $return) }}">@csrf<x-button type="submit">Confirm completion</x-button></form></x-modal>@endif
        @if(in_array($return->status, [\App\Enums\ReturnStatus::Pending, \App\Enums\ReturnStatus::Approved]))<x-button variant="secondary" @click="$dispatch('open-modal', 'reject-return')">Reject return</x-button><x-modal name="reject-return" title="Reject return"><form method="POST" action="{{ route('returns.reject', $return) }}" class="space-y-5">@csrf<x-input name="reason" label="Rejection reason" required maxlength="255" /><x-button type="submit" variant="danger">Confirm rejection</x-button></form></x-modal>@endif
    @endcan
    </div>
    @if(!$eligible && in_array($return->status, [\App\Enums\ReturnStatus::Pending, \App\Enums\ReturnStatus::Approved]))<p role="alert" class="mb-6 text-sm text-danger">The three-day return window has expired. This return can no longer be approved or completed.</p>@endif
    <x-card title="Processing history"><ul class="space-y-3 text-sm"><li>Created: {{ $return->return_date->format('d M Y H:i:s') }}</li>@if($return->approved_at)<li>Approved: {{ $return->approved_at->format('d M Y H:i:s') }}</li>@endif @if($return->completed_at)<li>Completed: {{ $return->completed_at->format('d M Y H:i:s') }}</li>@endif @if($return->rejected_at)<li>Rejected: {{ $return->rejected_at->format('d M Y H:i:s') }} — {{ $return->rejection_reason }}</li>@endif</ul></x-card>
</x-layouts.app>
