<x-layouts.app :title="$user->exists ? 'Edit staff member' : 'Add staff member'">
    <a href="{{ route('users.index') }}" class="text-sm underline">Staff &amp; access</a><h1 class="mb-6 mt-2 text-3xl font-bold">{{ $user->exists ? 'Edit staff member' : 'Add staff member' }}</h1>
    @if(session('status'))<p role="status" class="mb-5 rounded-lg border border-success p-4 text-sm text-success">{{ session('status') }}</p>@endif
    @if($errors->any())<div role="alert" class="mb-5 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <x-card><form method="POST" action="{{ $user->exists ? route('users.update', $user) : route('users.store') }}" class="space-y-5">@csrf @if($user->exists) @method('PUT')<input type="hidden" name="revision" value="{{ old('revision', $user->revision) }}">@endif
        <div class="grid gap-5 sm:grid-cols-2"><x-input name="name" label="Full name" :value="old('name', $user->name)" required maxlength="150" /><x-input name="email" label="Sign-in email" type="email" :value="old('email', $user->email)" required maxlength="191" autocomplete="off" /><x-input name="phone" label="Phone (optional)" :value="old('phone', $user->phone)" maxlength="30" /><x-select name="role_id" label="Role" required>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id', $user->role_id ?? $roles->firstWhere('slug', 'salesperson')?->id) == $role->id)>{{ $role->name }}</option>@endforeach</x-select><x-select name="is_active" label="Account status"><option value="1" @selected(old('is_active', $user->is_active ?? true))>Active</option><option value="0" @selected(! old('is_active', $user->is_active ?? true))>Inactive</option></x-select></div>
        @unless($user->exists)<x-input name="password" label="Temporary staff password" type="password" required minlength="10" maxlength="255" autocomplete="new-password" help="At least 10 characters, including letters and numbers. Share it privately; the staff member must change it after signing in." /><x-input name="password_confirmation" label="Confirm temporary password" type="password" required maxlength="255" autocomplete="new-password" />@endunless
        <p class="text-sm text-text-secondary">Changing email, role or account status revokes existing sessions. You cannot deactivate yourself or change your own role here.</p>
        <x-input name="current_password" label="Your administrator password" type="password" required maxlength="255" autocomplete="current-password" />
        <x-button type="submit">{{ $user->exists ? 'Save staff changes' : 'Create staff account' }}</x-button>
    </form></x-card>
    @if($user->exists && $user->id !== auth()->id())<div class="mt-7"><x-card title="Reset staff password"><p class="mb-5 text-sm">Set a temporary password and share it privately. Existing sessions and reset links will be revoked. This does not activate an inactive account.</p><form method="POST" action="{{ route('users.password', $user) }}" class="space-y-5">@csrf<input type="hidden" name="revision" value="{{ $user->revision }}"><x-input name="password" id="reset-password" label="New temporary password" type="password" required minlength="10" maxlength="255" autocomplete="new-password" /><x-input name="password_confirmation" id="reset-confirmation" label="Confirm temporary password" type="password" required maxlength="255" autocomplete="new-password" /><x-input name="current_password" id="reset-administrator-password" label="Your administrator password" type="password" required maxlength="255" autocomplete="current-password" /><x-button type="submit" variant="secondary">Set temporary password</x-button></form></x-card></div>@endif
</x-layouts.app>
