<x-layouts.app title="Expenses">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold">Expenses</h1><div class="flex flex-wrap gap-3">@can('expense-categories.manage')<x-action-link :href="route('expense-categories.index')" variant="secondary">Manage categories</x-action-link>@endcan @can('expenses.create')<x-action-link :href="route('expenses.create')">Record expense</x-action-link>@endcan</div></div>
    <p class="mb-6 text-sm text-text-secondary">Operating costs only. Supplier stock belongs in Purchases.</p>
    <form method="GET" class="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <x-input name="q" label="Number or description" :value="$filters['q'] ?? ''" maxlength="191" />
        <x-select name="category_id" label="Category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</x-select>
        <x-select name="recorded_by" label="Recorded by"><option value="">All recorders</option>@foreach($recorders as $recorder)<option value="{{ $recorder->id }}" @selected(($filters['recorded_by'] ?? '') == $recorder->id)>{{ $recorder->name }}</option>@endforeach</x-select>
        <x-input name="date_from" label="From date" type="date" :value="$filters['date_from'] ?? ''" />
        <x-input name="date_to" label="To date" type="date" :value="$filters['date_to'] ?? ''" />
        <div class="flex items-end gap-4"><x-button type="submit" variant="secondary">Filter</x-button><a href="{{ route('expenses.index') }}" class="py-3 text-sm underline">Reset</a></div>
    </form>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><caption class="sr-only">Operating expenses</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Expense', 'Date', 'Category', 'Amount (TZS)', 'Recorded by'] as $label)<th scope="col" class="p-4">{{ $label }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@forelse($expenses as $expense)<tr><th scope="row" class="max-w-xs break-words p-4 font-medium"><a href="{{ route('expenses.show', $expense) }}" class="underline">{{ $expense->expense_number }}</a><span class="mt-2 block text-text-secondary">{{ \Illuminate\Support\Str::limit($expense->description, 100) }}</span></th><td class="p-4">{{ $expense->expense_date->format('d M Y') }}</td><td class="p-4">{{ $expense->category->name }}</td><td class="p-4">{{ \App\Support\Money::format($expense->amount, false) }}</td><td class="p-4">{{ $expense->recorder->name }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-text-secondary">No expenses found.</td></tr>@endforelse</tbody></table></div><div class="border-t border-border p-5">{{ $expenses->links() }}</div></div>
</x-layouts.app>
