<x-layouts.app :title="$expense->expense_number">
    
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('expenses.index') }}" class="text-sm underline">Expenses</a><h1 class="mt-2 text-3xl font-bold">{{ $expense->expense_number }}</h1></div>@can('expenses.update')<x-action-link :href="route('expenses.edit', $expense)">Edit expense</x-action-link>@endcan</div>
    <x-card title="Expense details"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt>Category</dt><dd class="font-semibold">{{ $expense->category->name }}</dd></div><div><dt>Amount</dt><dd class="text-xl font-semibold">@money($expense->amount)</dd></div><div><dt>Expense date</dt><dd>{{ $expense->expense_date->format('d M Y') }}</dd></div><div><dt>Recorded by</dt><dd>{{ $expense->recorder->name }}</dd></div></dl><p class="mt-5 whitespace-pre-wrap break-words text-sm">{{ $expense->description ?? 'No description provided.' }}</p></x-card>
    <section class="mt-7"><h2 class="mb-4 text-xl font-semibold">Audit history</h2><div class="space-y-4">@foreach($history as $entry)
        @php($before = $entry->old_values ? json_decode($entry->old_values, true) : null)
        @php($after = json_decode($entry->new_values, true))
        <x-card><p class="mb-4 text-sm font-semibold">{{ $entry->action === 'CREATE_EXPENSE' ? 'Recorded' : 'Updated' }} by {{ $entry->actor_name }} · {{ $entry->created_at }}</p>
            <div class="relative overflow-x-auto"><table class="w-full min-w-[450px] text-left text-sm"><caption class="sr-only">Values recorded in this change</caption><thead><tr><th scope="col" class="p-2">Field</th>@if($before)<th scope="col" class="p-2">Before</th>@endif<th scope="col" class="p-2">After</th></tr></thead><tbody>@foreach(['amount' => 'Amount (TZS)', 'expense_date' => 'Expense date', 'category_name' => 'Category', 'description' => 'Description'] as $field => $label)<tr class="border-t border-border"><th scope="row" class="p-2 font-medium">{{ $label }}</th>@if($before)<td class="max-w-sm break-words p-2">{{ $before[$field] ?? '—' }}</td>@endif<td class="max-w-sm break-words p-2">{{ $after[$field] ?? '—' }}</td></tr>@endforeach</tbody></table></div>
        </x-card>@endforeach</div><div class="mt-5">{{ $history->links() }}</div></section>
</x-layouts.app>
