<x-layouts.app :title="ucfirst($type).' report'">
    <a href="{{ route('reports.index') }}" class="text-sm underline">Reports</a><div class="mb-6 mt-2 flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold">{{ ucfirst($type) }} report</h1><a href="{{ route('reports.export', ['type' => $type] + \Illuminate\Support\Arr::except($filters, 'page')) }}" class="rounded-lg bg-primary px-4 py-3 text-sm font-semibold">Download CSV</a></div>
    @if($errors->any())<div role="alert" class="mb-5 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <form method="GET" class="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        @if($type !== 'inventory')<x-input name="date_from" label="From date" type="date" :value="$filters['date_from']" required /><x-input name="date_to" label="To date (inclusive)" type="date" :value="$filters['date_to']" :max="now()->toDateString()" required />@endif
        @foreach($options as $field => $choices)
            @php($label = ['product'=>'Product name or code', 'variant'=>'Variant SKU', 'customer'=>'Customer name, code or phone', 'supplier'=>'Supplier name or code', 'category_id'=>'Category', 'size_id'=>'Size', 'colour_id'=>'Colour', 'salesperson_id'=>'Salesperson', 'recorded_by'=>'Recorded by', 'purchase_count_min'=>'Minimum completed sales', 'spent_min'=>'Minimum gross spend (TZS)', 'status'=>'Status', 'payment_method'=>'Payment method', 'stock_status'=>'Stock status'][$field])
            @if($choices !== null)<x-select :name="$field" :label="$label"><option value="">All</option>@foreach($choices as $value => $choice)<option value="{{ $value }}" @selected(($filters[$field] ?? '') == $value)>{{ $choice }}</option>@endforeach</x-select>
            @else<x-input :name="$field" :label="$label" :value="$filters[$field] ?? ''" maxlength="150" />@endif
        @endforeach
        <div class="flex items-end gap-4"><x-button type="submit" variant="secondary">Apply filters</x-button><a href="{{ route('reports.show', $type) }}" class="py-3 text-sm underline">Reset</a></div>
    </form>
    <p class="mb-5 text-sm leading-6 text-text-secondary">@if($type === 'inventory')Current stock balances, including archived and inactive catalogue records. Available = physical − reserved; this is not a historical stock snapshot or a guarantee that an item is active for sale.
    @elseif($type === 'customers')Completed sales in the selected period, before refunds and exchanges. Walk-ins are excluded. Customers with no sales in the period show zero; profile creation date does not limit this report.
    @elseif($type === 'profit')Completed adjustments affect their completion period; expenses use their expense date. Only sellable returns reverse cost. Damaged/defective goods retain their original cost. Exchange refunds are included once in completed refunds. This is an operational estimate, not full accounting.
    @else
    Product filters select matching documents; displayed amounts are full document totals, not just matching lines. Completed returns/refunds/exchanges use completion dates; unfinished documents use creation dates. Sales use completion/sale dates; purchases and expenses use their recorded business dates.@endif</p>
    @if($summary)
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach(\App\Services\ReportService::FINANCIAL_LABELS as $field => $label)<x-metric :label="$label" :value="$summary[$field]" money />@endforeach</div>
        <x-card title="Reconcile this period" class="mt-6"><p class="mb-4 text-sm">Net sales = gross sales + exchange payments − refunds. Adjusted COGS = original costs + replacement costs − sellable return/exchange costs. Gross profit = net sales − COGS. Estimated Net Profit = gross profit − expenses.</p><div class="flex flex-wrap gap-4">@foreach(['sales', 'refunds', 'returns', 'exchanges', 'expenses'] as $source)@if(app(\App\Services\ReportService::class)->allowed(auth()->user(), $source))<a class="text-sm underline" href="{{ route('reports.show', ['type'=>$source, 'date_from'=>$filters['date_from'], 'date_to'=>$filters['date_to']] + ($source === 'expenses' ? [] : ['status'=>'COMPLETED'])) }}">View {{ $source }}</a>@endif @endforeach</div></x-card>
    @else
        <p class="mb-3 text-sm">{{ $rows->total() }} matching records · Downloads include all matches up to 5,000 rows.</p>
        <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[750px] text-left text-sm"><caption class="sr-only">{{ ucfirst($type) }} report results</caption><thead class="border-b border-border bg-background"><tr>@foreach($columns as $label)<th scope="col" class="p-4">{{ $label }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@forelse($rows as $row)<tr>@foreach($row['values'] as $field => $value)<td class="max-w-sm break-words p-4">@if($field === 'number' && in_array($type, ['sales', 'purchases', 'expenses', 'returns', 'refunds', 'exchanges']))<a class="underline" href="{{ route($type.'.show', $row['id']) }}">{{ $value }}</a>@else{{ $value === '' ? '—' : $value }}@endif</td>@endforeach</tr>@empty<tr><td colspan="{{ count($columns) }}" class="p-10 text-center text-text-secondary">No matching records.</td></tr>@endforelse</tbody></table></div><div class="border-t border-border p-5">{{ $rows->links() }}</div></div>
    @endif
</x-layouts.app>
