<x-layouts.app :title="$refund->refund_number">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('refunds.index') }}" class="text-sm underline">Refunds</a><h1 class="mt-2 text-3xl font-bold">{{ $refund->refund_number }}</h1></div><span class="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold">{{ $refund->status->value }}</span></div>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <x-card title="Refund details"><p class="text-3xl font-bold">@money($refund->amount)</p><dl class="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-text-secondary">Original sale</dt><dd>{{ $refund->sale->sale_number }} · {{ \App\Services\SaleService::PAYMENT_METHODS[$refund->sale->payment_method] }}</dd></div><div><dt class="text-text-secondary">Requested by</dt><dd>{{ $refund->requester->name }}</dd></div><div><dt class="text-text-secondary">Reason</dt><dd class="break-words">{{ $refund->reason }}</dd></div><div><dt class="text-text-secondary">Refund method</dt><dd>{{ $refund->refund_method ? \App\Services\SaleService::PAYMENT_METHODS[$refund->refund_method] : 'Administrator will choose at approval' }}</dd></div><div><dt class="text-text-secondary">Related return</dt><dd>{{ $refund->saleReturn?->return_number ?? 'None' }}</dd></div><div><dt class="text-text-secondary">Payment reference</dt><dd class="break-words">{{ $refund->payment_reference ?? 'Not recorded' }}</dd></div></dl></x-card>
    <div class="relative my-6 overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full min-w-[500px] text-left text-sm"><caption class="sr-only">Refund allocation</caption><thead><tr><th scope="col" class="p-4">Item</th><th scope="col" class="p-4">Refund (TZS)</th><th scope="col" class="p-4">Available excluding this request</th></tr></thead><tbody>@foreach($refund->items as $item)<tr class="border-t border-border"><th scope="row" class="p-4 font-medium">{{ $item->saleItem->variant->sku }}<span class="block">{{ $item->saleItem->variant->product->name }}</span></th><td class="p-4">{{ \App\Support\Money::format($item->amount, false) }}</td><td class="p-4">@money($limits[$item->sale_item_id])</td></tr>@endforeach</tbody></table></div>
    <div class="mb-6 flex flex-wrap gap-3" x-data>
    @if(auth()->user()->role?->slug === 'administrator')
    @can('refunds.approve')
        @if($refund->status === \App\Enums\RefundStatus::Pending)<x-button @click="$dispatch('open-modal', 'approve-refund')">Approve refund</x-button><x-modal name="approve-refund" title="Approve refund and choose method"><form method="POST" action="{{ route('refunds.approve', $refund) }}" class="space-y-5">@csrf<p class="text-sm">Approve @money($refund->amount). This holds the amount against the sale's refundable balance. You may choose a different method from the original payment.</p><x-select name="refund_method" label="Refund method" required>@foreach(\App\Services\SaleService::PAYMENT_METHODS as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-select><x-button type="submit">Confirm approval</x-button></form></x-modal>@endif
        @if(in_array($refund->status, [\App\Enums\RefundStatus::Pending, \App\Enums\RefundStatus::Approved]))<x-button variant="secondary" @click="$dispatch('open-modal', 'close-refund')">Reject / cancel</x-button><x-modal name="close-refund" title="Close refund without payment"><form method="POST" action="{{ route('refunds.close', $refund) }}" class="space-y-5">@csrf<p class="text-sm">Use only if no money has been returned. Any approved hold will be released.</p><x-select name="status" label="Action"><option value="REJECTED">Reject</option><option value="CANCELLED">Cancel</option></x-select><x-input name="reason" label="Reason" required maxlength="255" /><x-button type="submit" variant="danger">Confirm closure</x-button></form></x-modal>@endif
    @endcan
    @can('refunds.complete')
        @if($refund->status === \App\Enums\RefundStatus::Approved)<x-button @click="$dispatch('open-modal', 'complete-refund')">Record payment completion</x-button><x-modal name="complete-refund" title="Confirm money has been returned"><form method="POST" action="{{ route('refunds.complete', $refund) }}" class="space-y-5">@csrf<p class="text-sm">Return @money($refund->amount) by {{ \App\Services\SaleService::PAYMENT_METHODS[$refund->refund_method] }} outside the system before completing this step.</p><x-input name="payment_reference" label="Payment reference (optional)" maxlength="191" /><label class="flex gap-3 text-sm"><input type="checkbox" name="payment_returned" value="1" required> I confirm the money was returned using the approved method.</label><x-button type="submit">Confirm completion</x-button></form></x-modal>@endif
    @endcan
    @endif
    </div>
    <x-card title="Processing history"><ul class="space-y-3 text-sm"><li>Requested: {{ $refund->created_at->format('d M Y H:i:s') }}</li>@if($refund->approved_at)<li>Approved: {{ $refund->approved_at->format('d M Y H:i:s') }}</li>@endif @if($refund->processed_at)<li>Completed: {{ $refund->processed_at->format('d M Y H:i:s') }}</li>@endif @if($refund->closed_at)<li>Closed: {{ $refund->closed_at->format('d M Y H:i:s') }} — {{ $refund->closure_reason }}</li>@endif</ul></x-card>
</x-layouts.app>
