<x-layouts.app :title="$customer->exists ? 'Edit customer' : 'Add customer'">
    <a href="{{ route('customers.index') }}" class="mb-5 inline-block text-sm underline">Back to customers</a><h1 class="mb-7 text-3xl font-bold">{{ $customer->exists ? 'Edit customer' : 'Add customer' }}</h1>
    <x-card class="max-w-3xl"><form method="POST" action="{{ $customer->exists ? route('customers.update', $customer) : route('customers.store') }}" class="space-y-6">@csrf @if($customer->exists) @method('PUT') @endif
        @if($errors->any())<div role="alert" class="text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
        <x-input name="full_name" label="Full name" :value="old('full_name', $customer->full_name)" maxlength="191" required />
        <div class="grid gap-5 sm:grid-cols-2"><x-input name="phone" label="Phone (optional)" type="tel" :value="old('phone', $customer->phone)" maxlength="30" /><x-input name="whatsapp_number" label="WhatsApp number (optional)" type="tel" :value="old('whatsapp_number', $customer->whatsapp_number)" maxlength="30" /></div>
        <p class="text-sm text-text-secondary">Use a consistent country-code format to help identify duplicates. Spaces, brackets and hyphens are removed when saved.</p>
        @error('allow_duplicate')<label class="flex gap-3 text-sm"><input type="checkbox" name="allow_duplicate" value="1" required> I checked the existing profile and want to save this as a separate customer.</label>@enderror
        <x-input name="location" label="Location (optional)" :value="old('location', $customer->location)" maxlength="255" />
        <div class="grid gap-5 sm:grid-cols-2"><x-select name="preferred_size_id" label="Preferred size"><option value="">No preference</option>@foreach($sizes as $size)<option value="{{ $size->id }}" @selected((string) old('preferred_size_id', $customer->preferred_size_id) === (string) $size->id)>{{ $size->name }}</option>@endforeach</x-select><x-select name="preferred_colour_id" label="Preferred colour"><option value="">No preference</option>@foreach($colours as $colour)<option value="{{ $colour->id }}" @selected((string) old('preferred_colour_id', $customer->preferred_colour_id) === (string) $colour->id)>{{ $colour->name }}</option>@endforeach</x-select></div>
        <fieldset><legend class="mb-3 text-sm font-medium">Category preferences</legend><div class="flex flex-wrap gap-4">@forelse($categories as $category)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="category_ids[]" value="{{ $category->id }}" @checked(in_array($category->id, (array) old('category_ids', $customer->categories->modelKeys())))>{{ $category->name }}</label>@empty<p class="text-sm text-text-secondary">No active categories available.</p>@endforelse</div></fieldset>
        <div><label for="notes" class="mb-2 block text-sm font-medium">Notes (optional)</label><textarea id="notes" name="notes" rows="3" maxlength="5000" class="w-full rounded-lg border border-border px-3 py-2 text-sm">{{ old('notes', $customer->notes) }}</textarea></div>
        <input type="hidden" name="marketing_opt_in" value="0"><label class="flex items-start gap-3 text-sm"><input type="checkbox" name="marketing_opt_in" value="1" @checked(old('marketing_opt_in', $customer->marketing_opt_in))> Customer explicitly agreed to receive marketing messages.</label>
        @if($customer->exists)<x-select name="is_active" label="Status"><option value="1" @selected(old('is_active', $customer->is_active))>Active</option><option value="0" @selected(!old('is_active', $customer->is_active))>Inactive</option></x-select>@endif
        <x-button type="submit">{{ $customer->exists ? 'Save changes' : 'Create customer' }}</x-button>
    </form></x-card>
</x-layouts.app>
