<x-layouts.app title="Customers">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold">Customers</h1><div class="flex flex-wrap gap-3" x-data><x-button type="button" variant="secondary" @click="$dispatch('open-modal', 'quick-customer')">Quick create</x-button><x-action-link :href="route('customers.create')">Add customer</x-action-link></div></div>
    <p class="mb-6 text-sm text-text-secondary">Register customers who want a profile. Walk-in sales will not require registration.</p>
    <form method="GET" class="mb-6 flex flex-wrap items-end gap-4"><div class="min-w-0 flex-1"><x-input name="q" label="Search" :value="$filters['q'] ?? ''" placeholder="Name, code, phone or WhatsApp" maxlength="191" /></div><x-select name="status" label="Status"><option value="">All customers</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></x-select><x-button type="submit" variant="secondary">Filter</x-button></form>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><caption class="sr-only">Customer profiles</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Customer', 'Phone', 'WhatsApp', 'Status'] as $heading)<th scope="col" class="p-5">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@forelse($customers as $customer)<tr><th scope="row" class="max-w-xs break-words p-5 font-medium"><a href="{{ route('customers.show', $customer) }}" class="underline">{{ $customer->full_name }}</a><span class="mt-1 block text-xs text-text-secondary">{{ $customer->customer_code }}</span></th><td class="p-5">{{ $customer->phone ?? 'Not provided' }}</td><td class="p-5">{{ $customer->whatsapp_number ?? 'Not provided' }}</td><td class="p-5"><x-badge :tone="$customer->is_active ? 'success' : 'warning'">{{ $customer->is_active ? 'Active' : 'Inactive' }}</x-badge></td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-text-secondary">No customers found.</td></tr>@endforelse</tbody></table></div><div class="border-t border-border p-5">{{ $customers->links() }}</div></div>
    <x-modal name="quick-customer" title="Quick customer registration" x-init="{{ $errors->any() ? '$el.showModal()' : '' }}">
        <form method="POST" action="{{ route('customers.store') }}" class="space-y-5">@csrf
            @if($errors->any())<div role="alert" class="text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
            <x-input name="full_name" label="Full name" :value="old('full_name')" required maxlength="191" />
            <x-input name="phone" label="Phone (optional)" type="tel" :value="old('phone')" maxlength="30" />
            <x-input name="whatsapp_number" label="WhatsApp number (optional)" type="tel" :value="old('whatsapp_number')" maxlength="30" />
            @error('allow_duplicate')<label class="flex gap-3 text-sm"><input type="checkbox" name="allow_duplicate" value="1" required> I checked the existing profile and want to create a separate customer.</label>@enderror
            <p class="text-sm text-text-secondary">Marketing consent starts off. Use the full form to record preferences and explicit consent.</p><x-button type="submit">Create customer</x-button>
        </form>
    </x-modal>
</x-layouts.app>
