@php($isOrder = $isOrder ?? false)
<x-layouts.app :title="$isOrder ? 'New order' : 'Point of sale'">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold">{{ $isOrder ? 'New order' : 'Point of sale' }}</h1><a href="{{ route($isOrder ? 'orders.index' : 'sales.index') }}" class="text-sm underline">{{ $isOrder ? 'Orders' : 'Sales history' }}</a></div>
    <form method="POST" action="{{ route($isOrder ? 'orders.store' : 'sales.review') }}" x-data="saleForm(@js($selectedCustomer), @js($lines), @js(route($isOrder ? 'orders.lookup' : 'sales.lookup')))" class="space-y-6">@csrf<input type="hidden" name="request_key" value="{{ $requestKey }}">
        @if($errors->any())<div role="alert" class="rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
        <noscript>Enable JavaScript to search products and build the cart.</noscript>
        <x-card title="Find products"><label for="product-search" class="mb-2 block text-sm font-medium">Product name or SKU</label><div class="flex gap-3"><input id="product-search" x-model="query" @keydown.enter.prevent="search('variant')" maxlength="191" class="min-w-0 flex-1 rounded-lg border border-border px-3 py-2 text-sm"><x-button type="button" variant="secondary" @click="search('variant')">Search products</x-button></div><p role="status" class="mt-3 text-sm text-text-secondary" x-text="error"></p>
            <div class="mt-4 grid gap-3 sm:grid-cols-2"><template x-for="result in results" :key="result.id"><button type="button" @click="add(result)" :disabled="result.available < 1" class="rounded-lg border border-border p-4 text-left text-sm hover:bg-selected disabled:opacity-50"><span class="block break-words font-semibold" x-text="result.label"></span><span class="mt-2 block" x-text="formatMoney(result.unit_price) + ' · Available: ' + result.available"></span></button></template></div>
        </x-card>
        <x-card title="Cart"><p x-show="!lines.length" class="text-sm text-text-secondary">Search for a product and select it to add a variant.</p><div class="space-y-4"><template x-for="(line, index) in lines" :key="line.product_variant_id"><fieldset class="min-w-0 rounded-lg border border-border p-4"><legend class="max-w-full break-words px-2 text-sm font-semibold" x-text="line.label"></legend><input type="hidden" :name="`items[${index}][product_variant_id]`" :value="line.product_variant_id"><div class="grid gap-4 sm:grid-cols-3">@foreach(['quantity' => 'Quantity', 'unit_price' => 'Unit selling price (TZS)', 'discount_amount' => 'Line discount (TZS)'] as $field => $label)<div><label :for="'{{ $field }}-' + index" class="mb-2 block text-sm font-medium">{{ $label }}</label><input :id="'{{ $field }}-' + index" :name="`items[${index}][{{ $field }}]`" x-model="line.{{ $field }}" inputmode="{{ $field === 'quantity' ? 'numeric' : 'decimal' }}" required class="w-full min-w-0 rounded-lg border border-border px-3 py-2 text-sm"></div>@endforeach</div><button type="button" @click="lines.splice(index, 1)" class="mt-3 min-h-11 text-sm underline">Remove item</button></fieldset></template></div></x-card>
        <div class="grid gap-6 lg:grid-cols-2"><x-card title="Customer"><p class="mb-4 break-words text-sm font-semibold" x-text="customer.label"></p><input type="hidden" name="customer_id" :value="customer.id">@unless($isOrder)<x-button type="button" variant="secondary" @click="customer = {id:'',label:'Walk-in'}">Use walk-in</x-button>@endunless<label for="customer-search" class="mb-2 mt-5 block text-sm font-medium">Find registered customer</label><div class="flex gap-3"><input id="customer-search" x-model="customersQuery" @keydown.enter.prevent="search('customer')" maxlength="191" class="min-w-0 flex-1 rounded-lg border border-border px-3 py-2 text-sm"><x-button type="button" variant="secondary" @click="search('customer')">Search</x-button></div><ul class="mt-3 max-h-48 overflow-y-auto"><template x-for="result in customers" :key="result.id"><li><button type="button" @click="customer = result; customers = []" class="w-full border-b border-border py-3 text-left text-sm" x-text="result.label"></button></li></template></ul>@can('customers.create')<a href="{{ route('customers.index') }}" target="_blank" rel="noopener" class="mt-4 inline-block text-sm underline">Register customer in a new tab</a>@endcan</x-card>
        @if($isOrder)<x-card title="Delivery"><x-input name="delivery_address" label="Delivery address (optional)" :value="old('delivery_address')" maxlength="255" /><div class="mt-5"><x-input name="notes" label="Notes (optional)" :value="old('notes')" maxlength="5000" /></div><p class="mt-5 text-sm text-text-secondary">A registered customer is required. Saving an order does not reserve stock or record revenue.</p></x-card>@else<x-card title="Payment"><x-select name="payment_method" label="Payment method" required><option value="">Select method</option>@foreach(\App\Services\SaleService::PAYMENT_METHODS as $value => $label)<option value="{{ $value }}" @selected(old('payment_method') === $value)>{{ $label }}</option>@endforeach</x-select><div class="mt-5"><x-input name="payment_reference" label="Payment reference (optional)" :value="old('payment_reference')" maxlength="191" /></div><div class="mt-5"><x-input name="notes" label="Notes (optional)" :value="old('notes')" maxlength="5000" /></div><p class="mt-5 text-sm text-text-secondary">Payment is collected outside the system. Recording a method does not verify payment.</p></x-card>@endif</div>
        <div class="flex flex-wrap items-center gap-5"><x-button type="submit" x-bind:disabled="!lines.length">{{ $isOrder ? 'Save order' : 'Review sale total' }}</x-button><p class="text-sm text-text-secondary">{{ $isOrder ? 'Review the saved total before confirming stock.' : 'Stock is checked again when you complete the sale.' }}</p></div>
    </form>
</x-layouts.app>
