<x-layouts.app title="Review sale">
    <a href="{{ route('sales.create') }}" class="mb-5 inline-block text-sm underline">Back to cart</a><h1 class="mb-7 text-3xl font-bold">Review sale</h1>
    <x-card class="mb-6"><p class="text-sm">Customer: <strong>{{ $customer?->full_name ?? 'Walk-in' }}</strong></p><p class="mt-3 text-sm">Payment: {{ \App\Services\SaleService::PAYMENT_METHODS[$data['payment_method']] }}</p>@if($data['payment_reference'])<p class="mt-3 break-words text-sm">Reference: {{ $data['payment_reference'] }}</p>@endif</x-card>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><caption class="sr-only">Review sale amounts</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Product / SKU', 'Quantity', 'Unit price (TZS)', 'Discount (TZS)', 'Line total (TZS)'] as $label)<th scope="col" class="p-5">{{ $label }}</th>@endforeach</tr></thead><tbody class="divide-y divide-border">@foreach($totals['items'] as $line)<tr><th scope="row" class="max-w-xs break-words p-5 font-medium">{{ $variants[$line['product_variant_id']]->product->name }}<span class="mt-1 block text-xs">{{ $variants[$line['product_variant_id']]->sku }}</span></th>@foreach(['quantity', 'unit_price', 'discount_amount', 'line_total'] as $field)<td class="p-5">{{ $field === 'quantity' ? $line[$field] : \App\Support\Money::format($line[$field], false) }}</td>@endforeach</tr>@endforeach</tbody></table></div><div class="border-t border-border p-5 text-right"><p class="text-sm">Subtotal: @money($totals['subtotal']) · Discount: @money($totals['discount_total'])</p><p class="mt-3 text-xl font-bold">Total: @money($totals['total_amount'])</p></div></div>
    <form method="POST" action="{{ route('sales.store') }}" class="mt-6 space-y-5">@csrf
        @foreach(['request_key', 'customer_id', 'payment_method', 'payment_reference', 'notes'] as $field)<input type="hidden" name="{{ $field }}" value="{{ $data[$field] }}">@endforeach
        @foreach($data['items'] as $index => $item)@foreach($item as $field => $value)<input type="hidden" name="items[{{ $index }}][{{ $field }}]" value="{{ $value }}">@endforeach @endforeach
        <label class="flex items-start gap-3 text-sm"><input type="checkbox" required name="payment_collected" value="1"> I have collected the payment and checked the items and total.</label><p class="text-sm text-text-secondary">Completion records this sale permanently. Cancellation is not currently available.</p><x-button type="submit">Complete sale</x-button>
    </form>
</x-layouts.app>
