<x-layouts.app title="Sale details">
    <div class="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-3xl font-bold">Sale {{ strtolower($sale->status->value) }}</h1><p class="mt-3 text-sm text-text-secondary">{{ $sale->sale_number }}</p></div><x-action-link :href="route('sales.create')">New sale</x-action-link></div>
    @if(session('status'))<p role="status" class="mb-5 rounded-lg border border-success bg-surface p-4 text-sm">{{ session('status') }}</p>@endif
    <x-card class="mb-6"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-text-secondary">Customer</dt><dd class="mt-1">{{ $sale->customer?->full_name ?? 'Walk-in' }}</dd></div><div><dt class="text-text-secondary">Date / Staff</dt><dd class="mt-1">{{ $sale->sale_date->format('d M Y H:i') }} · {{ $sale->salesperson->name }}</dd></div><div><dt class="text-text-secondary">Payment (recorded manually)</dt><dd class="mt-1">{{ \App\Services\SaleService::PAYMENT_METHODS[$sale->payment_method] }}</dd></div><div><dt class="text-text-secondary">Reference</dt><dd class="mt-1 break-words">{{ $sale->payment_reference ?? 'Not provided' }}</dd></div></dl>@if($sale->notes)<p class="mt-5 break-words text-sm">{{ $sale->notes }}</p>@endif</x-card>
    <div class="overflow-hidden rounded-xl border border-border bg-surface"><div class="relative overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><caption class="sr-only">Sale item snapshots</caption><thead class="border-b border-border bg-background"><tr>@foreach(['Product / SKU', 'Quantity', 'Unit price', 'Discount', 'Line total'] as $label)<th scope="col" class="p-5">{{ $label }}</th>@endforeach @can('products.view_cost')<th scope="col" class="p-5">Unit cost</th>@endcan</tr></thead><tbody class="divide-y divide-border">@foreach($sale->items as $item)<tr><th scope="row" class="max-w-xs break-words p-5 font-medium">{{ $item->variant->product->name }}<span class="mt-1 block text-xs">{{ $item->variant->sku }}</span></th>@foreach(['quantity', 'unit_price', 'discount_amount', 'line_total'] as $field)<td class="p-5">{{ $item->$field }}</td>@endforeach @can('products.view_cost')<td class="p-5">{{ $item->unit_cost }}</td>@endcan</tr>@endforeach</tbody></table></div><div class="border-t border-border p-5 text-right"><p class="text-sm">Subtotal: TZS {{ $sale->subtotal }} · Discount: TZS {{ $sale->discount_total }}</p><p class="mt-3 text-xl font-bold">Total: TZS {{ $sale->total_amount }}</p>@can('products.view_cost')<p class="mt-3 text-sm">COGS: TZS {{ $sale->total_cogs }} · Gross profit: TZS {{ $sale->gross_profit }}</p>@endcan</div></div>
    @can('returns.create')
    <div class="mt-6"><x-action-link :href="route('returns.create', ['sale_number' => $sale->sale_number])">Start return</x-action-link></div>
    <x-card title="Return history" class="mt-6"><ul class="space-y-3 text-sm">@forelse($sale->returns as $return)<li><a class="underline" href="{{ route('returns.show', $return) }}">{{ $return->return_number }}</a> · {{ $return->status->value }}</li>@empty<li>No returns recorded.</li>@endforelse</ul></x-card>
    @endcan
    @can('refunds.create')
    <div class="mt-6"><x-action-link :href="route('refunds.create', ['sale_number' => $sale->sale_number])">Request refund</x-action-link></div>
    <x-card title="Refund history" class="mt-6"><ul class="space-y-3 text-sm">@forelse($sale->refunds as $refund)<li><a class="underline" href="{{ route('refunds.show', $refund) }}">{{ $refund->refund_number }}</a> · {{ $refund->status->value }} · TZS {{ $refund->amount }}</li>@empty<li>No refunds recorded.</li>@endforelse</ul></x-card>
    @endcan
    <a href="{{ route('sales.index') }}" class="mt-6 inline-block text-sm underline">Back to sales history</a>
</x-layouts.app>
