<x-layouts.app :title="$order->order_number">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('orders.index') }}" class="text-sm underline">Orders</a><h1 class="mt-2 text-3xl font-bold">{{ $order->order_number }}</h1></div><span class="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold">{{ str_replace('_', ' ', $order->status->value) }}</span></div>
    @if($errors->any())<div role="alert" class="mb-5 rounded-lg border border-danger p-4 text-sm text-danger">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <div class="grid gap-6 lg:grid-cols-2"><x-card title="Customer and delivery"><p class="font-semibold">{{ $order->customer->full_name }}</p><p class="mt-3 break-words text-sm">{{ $order->delivery_address ?? 'No delivery address recorded.' }}</p><p class="mt-3 break-words text-sm">{{ $order->notes }}</p><p class="mt-4 text-sm text-text-secondary">Staff: {{ $order->salesperson?->name ?? 'Unavailable' }}</p></x-card>
    <x-card title="Order total"><p class="text-3xl font-bold">@money($order->total_amount)</p><p class="mt-3 text-sm">Subtotal @money($order->subtotal) · Discount @money($order->discount_total)</p><p class="mt-3 text-sm">Payment: {{ $order->payment_status }} @if($order->payment_method) · {{ \App\Services\SaleService::PAYMENT_METHODS[$order->payment_method] }}@endif</p>@if($order->payment_reference)<p class="mt-2 break-words text-sm">Reference: {{ $order->payment_reference }}</p>@endif
    @if($order->sale)<p class="mt-4 text-sm">Sale: @if(auth()->user()->hasPermission('sales.create') && (auth()->user()->hasPermission('sales.view_all') || $order->sale->salesperson_id === auth()->id()))<a class="underline" href="{{ route('sales.show', $order->sale) }}">{{ $order->sale->sale_number }}</a>@else{{ $order->sale->sale_number }}@endif</p>@else<p class="mt-4 text-sm text-text-secondary">No sale recorded yet.</p>@endif</x-card></div>
    <div class="relative my-6 overflow-x-auto rounded-xl border border-border bg-surface"><table class="w-full min-w-[600px] text-left text-sm"><caption class="sr-only">Order items and reservations</caption><thead><tr>@foreach(['Item', 'Quantity', 'Unit price (TZS)', 'Discount (TZS)', 'Line total (TZS)', 'Reservation'] as $label)<th scope="col" class="p-4">{{ $label }}</th>@endforeach</tr></thead><tbody>@foreach($order->items as $item)<tr class="border-t border-border"><th scope="row" class="p-4 font-medium">{{ $item->variant->sku }}<span class="block text-text-secondary">{{ $item->variant->product->name }}</span></th><td class="p-4">{{ $item->quantity }}</td><td class="p-4">{{ \App\Support\Money::format($item->unit_price, false) }}</td><td class="p-4">{{ \App\Support\Money::format($item->discount_amount, false) }}</td><td class="p-4">{{ \App\Support\Money::format($item->line_total, false) }}</td><td class="p-4">{{ $order->reservations->firstWhere('order_item_id', $item->id)?->status ?? 'Not reserved' }}</td></tr>@endforeach</tbody></table></div>
    <div class="mb-6 flex flex-wrap gap-3" x-data>
    @if($order->status === \App\Enums\OrderStatus::New)<x-button @click="$dispatch('open-modal', 'confirm-order')">Confirm and reserve stock</x-button><x-modal name="confirm-order" title="Confirm this order?"><p class="mb-5 text-sm">Reserve the quantities above for this customer. Physical stock remains unchanged.</p><form method="POST" action="{{ route('orders.confirm', $order) }}">@csrf<x-button type="submit">Reserve stock</x-button></form></x-modal>@endif
    @if($order->status === \App\Enums\OrderStatus::Confirmed)<x-button @click="$dispatch('open-modal', 'order-payment')">Record full payment</x-button><x-modal name="order-payment" title="Record full payment"><form method="POST" action="{{ route('orders.paid', $order) }}" class="space-y-5">@csrf<p class="text-sm">Confirm that @money($order->total_amount) has been collected outside the system. This does not verify a provider payment.</p><x-select name="payment_method" label="Payment method" required>@foreach(\App\Services\SaleService::PAYMENT_METHODS as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</x-select><x-input name="payment_reference" label="Reference (optional)" maxlength="191" /><label class="flex gap-3 text-sm"><input type="checkbox" required> I confirm the full payment was received.</label><x-button type="submit">Mark payment received</x-button></form></x-modal>@endif
    @if($order->status === \App\Enums\OrderStatus::PaymentReceived && !$order->sale)@can('sales.create')<x-button @click="$dispatch('open-modal', 'convert-order')">Convert to sale</x-button><x-modal name="convert-order" title="Complete the paid sale?"><p class="mb-5 text-sm">Deduct the reserved stock and record the sale for @money($order->total_amount).</p><form method="POST" action="{{ route('orders.convert', $order) }}">@csrf<x-button type="submit">Complete sale</x-button></form></x-modal>@endcan
    @endif
    @php($next = $order->sale ? match($order->status) { \App\Enums\OrderStatus::PaymentReceived => 'PREPARING', \App\Enums\OrderStatus::Preparing => 'OUT_FOR_DELIVERY', \App\Enums\OrderStatus::OutForDelivery => 'DELIVERED', default => null } : null)
    @if($next)<form method="POST" action="{{ route('orders.status', $order) }}">@csrf<input type="hidden" name="status" value="{{ $next }}"><x-button type="submit">Mark {{ strtolower(str_replace('_', ' ', $next)) }}</x-button></form>@endif
    @if($order->payment_status === 'UNPAID' && in_array($order->status, [\App\Enums\OrderStatus::New, \App\Enums\OrderStatus::Confirmed]))<x-button variant="secondary" @click="$dispatch('open-modal', 'cancel-order')">Cancel order</x-button><x-modal name="cancel-order" title="Cancel unpaid order"><form method="POST" action="{{ route('orders.cancel', $order) }}" class="space-y-5">@csrf<p class="text-sm">Any active reservations for this order will be released.</p><x-input name="reason" label="Cancellation reason" required maxlength="255" /><x-button type="submit" variant="danger">Cancel and release stock</x-button></form></x-modal>@endif
    </div>
    <x-card title="Order timeline"><ol class="space-y-5">@foreach($timeline as $event)<li class="border-l-2 border-border pl-4"><p class="text-sm font-semibold">{{ ucwords(strtolower(str_replace('_', ' ', $event->action === 'ORDER_STATUS_CHANGED' ? (json_decode($event->new_values, true)['status'] ?? $event->action) : $event->action))) }}</p><p class="mt-1 text-xs text-text-secondary">{{ $event->created_at }} · {{ $event->name }}</p>@if($reason = (json_decode($event->new_values ?? '{}', true)['reason'] ?? null))<p class="mt-2 break-words text-sm">{{ $reason }}</p>@endif</li>@endforeach</ol></x-card>
</x-layouts.app>
